version: '3.8'

services:
  vosk-gpu:
    image: sskorol/vosk-server:0.3.32-pc
    volumes:
      - ./model:/opt/vosk-server/model
    environment:
      - SAMPLE_RATE=16000
      - PYTHONBUFFERED=1
      - PYTHONENCODING=utf-8
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    network_mode: "host"
