version: '3.3'

services:
  google_stt:
    restart: always 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    #ports:
    #  - 4212:4212
    environment:
      - TZ=Europe/Moscow
      - PORT=4212
